// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uihnnrhuqjeybtvinzkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpaG5ucmh1cWpleWJ0dmluemttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4ODcyMTMsImV4cCI6MjA3NzQ2MzIxM30.YRV3uWj2uuRzd920XKyxISRTZ1GN6IuVAlhpmxNWTE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});